version: 2
sources:
  
  - name: gz_raw_data
    tables:
      - name: raw_gz_product_copy
        description: product
      - name: raw_gz_sales_copy
        description: sales
      - name: raw_gz_ship_copy
        description: ship

models: 
  - name: stg_gz_raw_data__raw_gz_product_copy
    description: find unique key

    tests:
      - unique:
          column_name: products_id
  - name: stg_gz_raw_data__raw_gz_ship_copy
    description: find unique key
    tests:
      - unique:
          column_name: orders_id
  - name: stg_gz_raw_data__raw_gz_sales_copy
    description: find unique key
    tests:
      - unique:
          column_name: "(orders_id || '_' || product_id)" 
  - name: finance_days
    description: Data analisys for finance team



    