version: 2
sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_product_copy
        description: product
      - name: raw_gz_sales_copy
        description: sales
      - name: raw_gz_ship_copy
        description: ship
